/** GENERATED FILE. DO NOT EDIT. This receipt is outside the packed engine. */
import type { HarvestReceipt } from "../receipt.ts";
export const RECEIPT: HarvestReceipt = {
  diagnostics: [
    {
      code: "symbolic-callback",
      detail: "bibliography-items",
      field: "environments.thebibliography.processContent",
      location: { byteEnd: 13832, byteStart: 13769, line: 375, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.checkboxes.processContent",
      location: { byteEnd: 1872, byteStart: 1810, line: 42, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.choices.processContent",
      location: { byteEnd: 1751, byteStart: 1689, line: 38, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.description.processContent",
      location: { byteEnd: 12908, byteStart: 12874, line: 354, utf16Column: 36 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.enumerate.processContent",
      location: { byteEnd: 12995, byteStart: 12961, line: 357, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.itemize.processContent",
      location: { byteEnd: 13112, byteStart: 13078, line: 360, utf16Column: 32 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.list.processContent",
      location: { byteEnd: 13250, byteStart: 13216, line: 362, utf16Column: 31 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.oneparcheckboxes.processContent",
      location: { byteEnd: 2123, byteStart: 2061, line: 50, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.oneparchoices.processContent",
      location: { byteEnd: 1996, byteStart: 1934, line: 46, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.parts.processContent",
      location: { byteEnd: 2237, byteStart: 2177, line: 54, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.questions.processContent",
      location: { byteEnd: 2605, byteStart: 2541, line: 66, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.subparts.processContent",
      location: { byteEnd: 2357, byteStart: 2294, line: 58, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.subsubparts.processContent",
      location: { byteEnd: 2483, byteStart: 2417, line: 62, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "list-items",
      field: "environments.trivlist.processContent",
      location: { byteEnd: 13182, byteStart: 13148, line: 361, utf16Column: 33 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "listings-inline",
      field: "macros.lstinline.argumentParser",
      location: { byteEnd: 272, byteStart: 242, line: 9, utf16Column: 18 },
      path: "packages/unified-latex-ctan/package/listings/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "minted-inline",
      field: "macros.inputminted.argumentParser",
      location: { byteEnd: 340, byteStart: 310, line: 10, utf16Column: 20 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "minted-inline",
      field: "macros.mint.argumentParser",
      location: { byteEnd: 235, byteStart: 205, line: 8, utf16Column: 13 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "minted-inline",
      field: "macros.mintinline.argumentParser",
      location: { byteEnd: 287, byteStart: 257, line: 9, utf16Column: 19 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-command",
      field: "conditionalMacros.scoped.argumentParser",
      location: { byteEnd: 14998, byteStart: 14957, line: 382, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-command",
      field: "macros.tikz.argumentParser",
      location: { byteEnd: 1277, byteStart: 1236, line: 38, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.axis.processContent",
      location: { byteEnd: 1738, byteStart: 1693, line: 52, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.behindforegroundpath.processContent",
      location: { byteEnd: 2669, byteStart: 2624, line: 81, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.pgflowlevelscope.processContent",
      location: { byteEnd: 2211, byteStart: 2166, line: 67, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.pgfmetadecoration.processContent",
      location: { byteEnd: 2780, byteStart: 2735, line: 85, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.pgfonlayer.processContent",
      location: { byteEnd: 2054, byteStart: 2009, line: 62, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.pgftransparencygroup.processContent",
      location: { byteEnd: 2555, byteStart: 2510, line: 77, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.pgfviewboxscope.processContent",
      location: { byteEnd: 2375, byteStart: 2330, line: 72, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.scope.processContent",
      location: { byteEnd: 1903, byteStart: 1858, line: 57, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "tikz-conditional-arguments",
      field: "environments.tikzpicture.processContent",
      location: { byteEnd: 1574, byteStart: 1529, line: 47, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "symbolic-callback",
      detail: "trim-boundaries",
      field: "environments.document.processContent",
      location: { byteEnd: 12761, byteStart: 12672, line: 348, utf16Column: 9 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unavailable-strategy",
      detail: "systeme content processing is deferred",
      field: "macros.systeme",
      location: { byteEnd: 228, byteStart: 140, line: 7, utf16Column: 5 },
      path: "packages/unified-latex-ctan/package/systeme/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.checkboxes.processContent",
      location: { byteEnd: 1872, byteStart: 1826, line: 42, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.choices.processContent",
      location: { byteEnd: 1751, byteStart: 1705, line: 38, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.document.processContent",
      location: { byteEnd: 12761, byteStart: 12688, line: 348, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.oneparcheckboxes.processContent",
      location: { byteEnd: 2123, byteStart: 2077, line: 50, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.oneparchoices.processContent",
      location: { byteEnd: 1996, byteStart: 1950, line: 46, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.parts.processContent",
      location: { byteEnd: 2237, byteStart: 2193, line: 54, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.questions.processContent",
      location: { byteEnd: 2605, byteStart: 2557, line: 66, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.subparts.processContent",
      location: { byteEnd: 2357, byteStart: 2310, line: 58, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.subsubparts.processContent",
      location: { byteEnd: 2483, byteStart: 2433, line: 62, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "ArrowFunction",
      field: "environments.thebibliography.processContent",
      location: { byteEnd: 13832, byteStart: 13785, line: 375, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "conditionalMacros.scoped.argumentParser",
      location: { byteEnd: 14998, byteStart: 14973, line: 382, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.axis.processContent",
      location: { byteEnd: 1738, byteStart: 1709, line: 52, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.behindforegroundpath.processContent",
      location: { byteEnd: 2669, byteStart: 2640, line: 81, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.description.processContent",
      location: { byteEnd: 12908, byteStart: 12890, line: 354, utf16Column: 52 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.enumerate.processContent",
      location: { byteEnd: 12995, byteStart: 12977, line: 357, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.itemize.processContent",
      location: { byteEnd: 13112, byteStart: 13094, line: 360, utf16Column: 48 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.list.processContent",
      location: { byteEnd: 13250, byteStart: 13232, line: 362, utf16Column: 47 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.pgflowlevelscope.processContent",
      location: { byteEnd: 2211, byteStart: 2182, line: 67, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.pgfmetadecoration.processContent",
      location: { byteEnd: 2780, byteStart: 2751, line: 85, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.pgfonlayer.processContent",
      location: { byteEnd: 2054, byteStart: 2025, line: 62, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.pgftransparencygroup.processContent",
      location: { byteEnd: 2555, byteStart: 2526, line: 77, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.pgfviewboxscope.processContent",
      location: { byteEnd: 2375, byteStart: 2346, line: 72, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.scope.processContent",
      location: { byteEnd: 1903, byteStart: 1874, line: 57, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.tikzpicture.processContent",
      location: { byteEnd: 1574, byteStart: 1545, line: 47, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "environments.trivlist.processContent",
      location: { byteEnd: 13182, byteStart: 13164, line: 361, utf16Column: 49 },
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "macros.inputminted.argumentParser",
      location: { byteEnd: 340, byteStart: 326, line: 10, utf16Column: 36 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "macros.lstinline.argumentParser",
      location: { byteEnd: 272, byteStart: 258, line: 9, utf16Column: 34 },
      path: "packages/unified-latex-ctan/package/listings/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "macros.mint.argumentParser",
      location: { byteEnd: 235, byteStart: 221, line: 8, utf16Column: 29 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "macros.mintinline.argumentParser",
      location: { byteEnd: 287, byteStart: 273, line: 9, utf16Column: 35 },
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "Identifier",
      field: "macros.tikz.argumentParser",
      location: { byteEnd: 1277, byteStart: 1252, line: 38, utf16Column: 25 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
    {
      code: "unsupported-expression",
      detail: "non-table declaration is retained as a diagnostic and never executed",
      field: "module",
      location: { byteEnd: 3109, byteStart: 2964, line: 93, utf16Column: 1 },
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
    },
  ],
  families: [
    {
      facets: { "argument-language": 6, classification: 6, "serialization-hint": 6, signature: 6 },
      family: "amsart",
      records: 6,
      signatures: 6,
      statuses: { "parent-asserted": 6 },
    },
    {
      facets: {
        "argument-language": 73,
        "content-processing": 6,
        "serialization-hint": 51,
        signature: 70,
      },
      family: "beamer",
      records: 73,
      signatures: 70,
      statuses: { "parent-asserted": 73 },
    },
    {
      facets: { "argument-language": 20, signature: 20 },
      family: "cleveref",
      records: 20,
      signatures: 20,
      statuses: { "parent-asserted": 20 },
    },
    {
      facets: {
        "argument-language": 30,
        "content-processing": 8,
        "serialization-hint": 15,
        signature: 30,
      },
      family: "exam",
      records: 30,
      signatures: 30,
      statuses: { "parent-asserted": 30 },
    },
    {
      facets: {
        "argument-language": 1,
        "content-processing": 1,
        "serialization-hint": 1,
        signature: 1,
      },
      family: "geometry",
      records: 1,
      signatures: 1,
      statuses: { "parent-asserted": 1 },
    },
    {
      facets: {
        "argument-language": 21,
        "content-processing": 1,
        "serialization-hint": 1,
        signature: 21,
      },
      family: "hyperref",
      records: 21,
      signatures: 21,
      statuses: { "parent-asserted": 21 },
    },
    {
      facets: {
        "argument-language": 183,
        classification: 33,
        "content-processing": 16,
        "serialization-hint": 88,
        signature: 157,
      },
      family: "latex2e",
      records: 183,
      signatures: 157,
      statuses: { "parent-asserted": 183 },
    },
    {
      facets: { "argument-language": 12, "content-processing": 1, signature: 11 },
      family: "listings",
      records: 12,
      signatures: 11,
      statuses: { "parent-asserted": 12 },
    },
    {
      facets: { "argument-language": 5, signature: 5 },
      family: "makeidx",
      records: 5,
      signatures: 5,
      statuses: { "parent-asserted": 5 },
    },
    {
      facets: {
        "argument-language": 119,
        classification: 53,
        "content-processing": 41,
        "serialization-hint": 8,
        signature: 84,
      },
      family: "mathtools",
      records: 119,
      signatures: 84,
      statuses: { "parent-asserted": 119 },
    },
    {
      facets: { "argument-language": 11, signature: 8 },
      family: "minted",
      records: 11,
      signatures: 8,
      statuses: { "parent-asserted": 11 },
    },
    {
      facets: { "argument-language": 3, "serialization-hint": 1, signature: 2 },
      family: "multicol",
      records: 3,
      signatures: 2,
      statuses: { "parent-asserted": 3 },
    },
    {
      facets: {
        "argument-language": 16,
        "content-processing": 31,
        "serialization-hint": 1,
        signature: 16,
      },
      family: "nicematrix",
      records: 16,
      signatures: 16,
      statuses: { "parent-asserted": 16 },
    },
    {
      facets: {
        "argument-language": 14,
        classification: 1,
        "content-processing": 1,
        signature: 14,
      },
      family: "systeme",
      records: 14,
      signatures: 14,
      statuses: { "parent-asserted": 14 },
    },
    {
      facets: { "argument-language": 1, "content-processing": 1, signature: 1 },
      family: "tabularx",
      records: 1,
      signatures: 1,
      statuses: { "parent-asserted": 1 },
    },
    {
      facets: {
        "argument-language": 256,
        classification: 11,
        "content-processing": 33,
        "serialization-hint": 18,
        signature: 256,
      },
      family: "tikz",
      records: 256,
      signatures: 256,
      statuses: { "parent-asserted": 256 },
    },
    {
      facets: {
        "argument-language": 28,
        classification: 1,
        "content-processing": 1,
        "serialization-hint": 15,
        signature: 28,
      },
      family: "xcolor",
      records: 28,
      signatures: 28,
      statuses: { "parent-asserted": 28 },
    },
    {
      facets: {
        "argument-language": 14,
        "content-processing": 1,
        "serialization-hint": 14,
        signature: 14,
      },
      family: "xparse",
      records: 14,
      signatures: 14,
      statuses: { "parent-asserted": 14 },
    },
  ],
  format: "texdig-registry/1",
  generator: { typescript: "6.0.3", version: "1" },
  inputs: [
    {
      license: "MIT",
      path: "LICENSE",
      sha256: "8945d330ddb16e332fedabf1dfe1ab5c7b371a6c0864ccc0c8663281685fae0b",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/index.ts",
      sha256: "e8027475ab5af0ca1a29eaeeef9311cc73957512bc61c980e1ff0a7ed736e1e5",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package.json",
      sha256: "384607da46ed95857d966c76e4f7b090059e5750270ab26a80a51ce3bcaf309c",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/amsart/provides.ts",
      sha256: "c520c5a371a6c71626f6fda639094e2fb7b928ec10db623896c2ede8073825f8",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/beamer/provides.ts",
      sha256: "34273a87cfa9677fe64cfeeb3a0b2404c1d8f91eaca16c09acee1266cc06219f",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/cleveref/provides.ts",
      sha256: "a2a29196ddf402162968d84065c92187133a36936e4440080a695bb829ded956",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/exam/provides.ts",
      sha256: "c052d8defbfe78ec6ae5b2ee6bb08cb34ad41a60a628f2463fba4e4d43843ae8",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/geometry/provides.ts",
      sha256: "8710bf9959009bd424c9acea7ec0879dd0cca4b8505033d31ed6ee652f209e5d",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/hyperref/provides.ts",
      sha256: "bdd09ed8d12f837527130ca3df0b924b883281f669f70d9b1b2c24baaa21d22c",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/latex2e/provides.ts",
      sha256: "bc90ee4ee6d23307fcf5ac98f97e71cc9d4ee9a256cabd781e12a12407b113ad",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/listings/provides.ts",
      sha256: "d54f4489e9947363545b560cce52390c8f244b14f2a92cf5dabac4365377cacf",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/makeidx/provides.ts",
      sha256: "ba35c1f73d343b4bd5c52f91f45f5a97983913321850c4fc6dc2c824dcf0c1b0",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/mathtools/provides.ts",
      sha256: "582c78be4a6aff984b8fca4b003fefd503ebf8b4f4b8a77ccc81dbe51349c0da",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/minted/provides.ts",
      sha256: "d99b3a816b59042df81070aa54d23b920839feb0ab858cba3c0628d66fc294f6",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/multicol/provides.ts",
      sha256: "481986b3163ac8d4d857717742022ebd6d71f3668f2ad5304d9efe4e4b19d58d",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/nicematrix/provides.ts",
      sha256: "bd3d0a4d813fe18b9e5e7631ff5a7518ea0624643e743b9696c3ace63f1d02c4",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/systeme/provides.ts",
      sha256: "fb46a6140b4dacef4190a5f7865b4748e1d545925c9dee5e3f5d53a086dc3fb2",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/tabularx/provides.ts",
      sha256: "566d5dad57dc8e23eb1234c35775258e6771c34c702b1b937ec4d598be349574",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/tikz/provides.ts",
      sha256: "b629d91ada14c1419a0b0648c86a22f070b6bcb50673a55bf25f7822ae6a7fa9",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/xcolor/provides.ts",
      sha256: "7c345645c766511238f8c42eebc5ee23ffb66e5abcdd346487d781392db6488f",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-ctan/package/xparse/provides.ts",
      sha256: "63a41c342b6b8e0a9d97e231d11cceeddf026ead52798a9fc1245a44329f0879",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-types/libs/info-specs.ts",
      sha256: "fd2771d451177bae7a8a07bd09556448af475efc0d718d793a9e7c3aa36d95cd",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-util-argspec/tests/argspec-parser.test.ts",
      sha256: "07afac815fbdee7f75eb646ab3827a61dd3fe790f350874b88704b1863155a96",
    },
    {
      license: "MIT",
      path: "packages/unified-latex-util-pegjs/grammars/xparse-argspec.pegjs",
      sha256: "84a51e3afc7c3ff0884ca588377153d740fd16a517e327d56b51a31a32ad85c8",
    },
  ],
  license: "MIT",
  outputs: [
    {
      path: "packages/texdig/src/registry/records/harvested/amsart.ts",
      sha256: "b70c61b5947f9c2cdcb6bd34e9c1d55bd3f89427ab1ba52128eee23684d3a343",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/beamer.ts",
      sha256: "2bcc306f4ce32d3975fb81b79a3a1c12390369ac10ed97eb1b18b80f3a9b945f",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/cleveref.ts",
      sha256: "7ed04730d8c11fbb536dcdb37adfa2ed453cb4e53e0ce7d3a432cb220cfa27e7",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/exam.ts",
      sha256: "88c36dae37b9e9eaf70330cbf30edf860d450dc6424cb9687dbb87ca0d57861d",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/geometry.ts",
      sha256: "69772fec26bd16a8a9898f9f9474de2e9f07229f6f2103d47b861ce496fd07c9",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/hyperref.ts",
      sha256: "3974bd7fdd7310a69b6ca59c5183f22ee376518872af0197203344ffd19e1940",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/index.ts",
      sha256: "350ccf66e98415eac459805f1e1c0431de04fdf55e3dbf0f9c8a5c9882eb6100",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/latex2e.ts",
      sha256: "7e857b5a00cc54131248008494c12462babba7664fd89ee340c217e493596bd4",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/listings.ts",
      sha256: "0f076628be62d7f5166b9a8ffacee35fb119787b0001c52c7994bfb9d1612529",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/makeidx.ts",
      sha256: "46c93373d7d4a478daaba8f9916887fff3dc13bc93fb4d03ff083afa726e2d42",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/mathtools.ts",
      sha256: "799b68b6f40834eb453dd4293faace33508f6e6a1dc8d557168f2ec615a31ef2",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/minted.ts",
      sha256: "6126cd77b4039505b5b040cc0981f91adc1bf0a318744b50a34c5c4e356e355f",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/multicol.ts",
      sha256: "52c3ddf33793e5727d17de27b90bd73dc78ea94d53ac1803fbe723426c06658c",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/nicematrix.ts",
      sha256: "7880777f29084d1e89e2ab128c3f9e2481522ca575efd2526b2325dd04732130",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/systeme.ts",
      sha256: "2df4467cc63b1d983fb34cae8a1fef6f6442fe6f11d0dc3584ff1519528d5302",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/tabularx.ts",
      sha256: "77bbb0ecfb06afa64f618bad6a7ed5aa3fee04a26610a0756c506588ed42474d",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/tikz.ts",
      sha256: "191308a79d21e2fa4056694e7dba3a58cade76d11a8f116593a0b879540e2383",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/xcolor.ts",
      sha256: "ea506ce2354051bd4028a1c293be3c4963c95eb54279a33b7ae9f5c41d609a8d",
    },
    {
      path: "packages/texdig/src/registry/records/harvested/xparse.ts",
      sha256: "326ffdcdfa09664f5e460e06b95e36b3deb75ae23eeb9ceae82a99fd4b7e8b9f",
    },
  ],
  repository: "https://github.com/siefkenj/unified-latex.git",
  revision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
};
