/** The `texdig/latex` surface. The first export is the bounded Phase 3 mechanics slice. */

export {
  MiniArticleStrictError as LatexStrictError,
  MiniArticleTimeoutError as LatexTimeoutError,
  MiniArticleStrictError,
  MiniArticleTimeoutError,
  parseMiniArticle as parseLatex,
  parseMiniArticle,
  realizeMiniArticle as realizeLatex,
  realizeMiniArticle,
  type MiniArticleCstNode as LatexCstNode,
  type MiniArticleCstNode,
  type MiniArticleDiagnostic as LatexDiagnostic,
  type MiniArticleDiagnostic,
  type MiniArticleDiagnosticCode as LatexDiagnosticCode,
  type MiniArticleDiagnosticCode,
  type MiniArticleGroupNode,
  type MiniArticleInvalidUtf8Residue,
  type MiniArticleLedgerEntry as LatexLedgerEntry,
  type MiniArticleLedgerEntry,
  type MiniArticleParseOptions as LatexParseOptions,
  type MiniArticleParseOptions,
  type MiniArticleParseResult as LatexParseResult,
  type MiniArticleParseResult,
  type MiniArticleRecoveredGroupNode,
  type MiniArticleResidue as LatexResidue,
  type MiniArticleResidue,
  type MiniArticleResidueLedgerEntry,
  type MiniArticleResidueNode,
  type MiniArticleRootNode as LatexRootNode,
  type MiniArticleRootNode,
  type MiniArticleStartRule as LatexStartRule,
  type MiniArticleStartRule,
  type MiniArticleSyntaxLedgerEntry,
  type MiniArticleToken as LatexToken,
  type MiniArticleToken,
  type MiniArticleTokenKind as LatexTokenKind,
  type MiniArticleTokenKind,
  type MiniArticleTokenNode,
  type MiniArticleTrivia as LatexTrivia,
  type MiniArticleTrivia,
  type MiniArticleTriviaKind as LatexTriviaKind,
  type MiniArticleTriviaKind,
  type MiniArticleTriviaLedgerEntry,
  type MiniArticleTriviaNode,
  type MiniArticleUnknownLexicalStateResidue,
  type MiniArticleUnclosedOpenResidue,
  type MiniArticleUnexpectedCloseResidue,
} from "./mini-article.js";
export { scanLatexLexicalStates, type LatexLexicalState } from "./lexical-state.js";
export * from "./sublanguages/index.js";
