/**
 * GENERATED FILE. DO NOT EDIT BY HAND.
 *
 * Source: authoritative archaeology tree unified-latex-utensils_tree.md.
 * Regenerate with scripts/generate-parent-oracle-manifest.ts and the pinned
 * snapshot and producer revisions recorded in README.md.
 */

export type ParentOracleProducer = "latex-utensils" | "unified-latex";
export type ParentOracleRole = "test" | "benchmark" | "test-helper";
export type ParentOracleCorrelationLabel = "parent-regression-correlated";

export interface ParentOracleFile {
  readonly id: string;
  readonly producer: ParentOracleProducer;
  readonly producerLineage: ParentOracleProducer;
  readonly upstreamRevision: string;
  readonly sourcePath: string;
  readonly license: "MIT";
  readonly role: ParentOracleRole;
  readonly correlationLabel: ParentOracleCorrelationLabel;
  readonly snapshotRevision: string;
  readonly snapshotShard: string;
  readonly snapshotContentStart: number;
  readonly snapshotContentEndInclusive: number;
}

export const PARENT_ORACLE_EXPECTED_FILE_COUNT = 82;

export const PARENT_ORACLE_FILES: readonly ParentOracleFile[] = Object.freeze([
  Object.freeze({
    id: "latex-utensils:test/assert_partially.ts",
    producer: "latex-utensils",
    producerLineage: "latex-utensils",
    upstreamRevision: "641a665b298260bd0f5a67ce5e7ec6d233b44043",
    sourcePath: "test/assert_partially.ts",
    license: "MIT",
    role: "test-helper",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s002_latex-utensils-tests",
    snapshotContentStart: 122,
    snapshotContentEndInclusive: 1050,
  }),
  Object.freeze({
    id: "latex-utensils:test/test_bibtex_parser.ts",
    producer: "latex-utensils",
    producerLineage: "latex-utensils",
    upstreamRevision: "641a665b298260bd0f5a67ce5e7ec6d233b44043",
    sourcePath: "test/test_bibtex_parser.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s002_latex-utensils-tests",
    snapshotContentStart: 1111,
    snapshotContentEndInclusive: 13296,
  }),
  Object.freeze({
    id: "latex-utensils:test/test_latex_log_parser.ts",
    producer: "latex-utensils",
    producerLineage: "latex-utensils",
    upstreamRevision: "641a665b298260bd0f5a67ce5e7ec6d233b44043",
    sourcePath: "test/test_latex_log_parser.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s002_latex-utensils-tests",
    snapshotContentStart: 13358,
    snapshotContentEndInclusive: 14287,
  }),
  Object.freeze({
    id: "latex-utensils:test/test_latex_parser_find.ts",
    producer: "latex-utensils",
    producerLineage: "latex-utensils",
    upstreamRevision: "641a665b298260bd0f5a67ce5e7ec6d233b44043",
    sourcePath: "test/test_latex_parser_find.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s002_latex-utensils-tests",
    snapshotContentStart: 54589,
    snapshotContentEndInclusive: 62328,
  }),
  Object.freeze({
    id: "latex-utensils:test/test_latex_parser.ts",
    producer: "latex-utensils",
    producerLineage: "latex-utensils",
    upstreamRevision: "641a665b298260bd0f5a67ce5e7ec6d233b44043",
    sourcePath: "test/test_latex_parser.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s002_latex-utensils-tests",
    snapshotContentStart: 14347,
    snapshotContentEndInclusive: 54525,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex/tests/parse.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex/tests/parse.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 68770,
    snapshotContentEndInclusive: 69625,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-builder/tests/unified-latex-builder.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-builder/tests/unified-latex-builder.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 569,
    snapshotContentEndInclusive: 4179,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-cli/tests/cli.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-cli/tests/cli.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 1073,
    snapshotContentEndInclusive: 5452,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-cli/tests/doc-examples.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-cli/tests/doc-examples.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 1808,
    snapshotContentEndInclusive: 3321,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/beamer.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/beamer.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 19488,
    snapshotContentEndInclusive: 21272,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/enumerate.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/enumerate.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 8909,
    snapshotContentEndInclusive: 10250,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/listings.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/listings.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 10331,
    snapshotContentEndInclusive: 11309,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/systeme.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/systeme.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s012_unified-latex-packages",
    snapshotContentStart: 9381,
    snapshotContentEndInclusive: 15422,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/tabular.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/tabular.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s013_unified-latex-packages",
    snapshotContentStart: 26825,
    snapshotContentEndInclusive: 27742,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/tikz.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/tikz.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 12891,
    snapshotContentEndInclusive: 16647,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-ctan/tests/xcolor.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-ctan/tests/xcolor.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s005_unified-latex-packages",
    snapshotContentStart: 18295,
    snapshotContentEndInclusive: 23494,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/argument-color-commands.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/argument-color-commands.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 12545,
    snapshotContentEndInclusive: 15456,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/argument-font-shaping-commands.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/argument-font-shaping-commands.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s005_unified-latex-packages",
    snapshotContentStart: 28723,
    snapshotContentEndInclusive: 33645,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/consistent-inline-math.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/consistent-inline-math.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 22515,
    snapshotContentEndInclusive: 24434,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/no-def.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/no-def.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 24513,
    snapshotContentEndInclusive: 25395,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/no-plaintext-operators.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/no-plaintext-operators.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 15552,
    snapshotContentEndInclusive: 18146,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/no-tex-display-math.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/no-tex-display-math.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s014_unified-latex-packages",
    snapshotContentStart: 22765,
    snapshotContentEndInclusive: 23690,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/no-tex-font-shaping-commands.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/no-tex-font-shaping-commands.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 14120,
    snapshotContentEndInclusive: 15554,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/obsolete-packages.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/obsolete-packages.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 15645,
    snapshotContentEndInclusive: 16669,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-lint/tests/prefer-setlength.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-lint/tests/prefer-setlength.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 18236,
    snapshotContentEndInclusive: 21045,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-prettier/tests/formatting-tikz.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-prettier/tests/formatting-tikz.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 20372,
    snapshotContentEndInclusive: 23989,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-prettier/tests/formatting.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-prettier/tests/formatting.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s003_unified-latex-packages",
    snapshotContentStart: 31600,
    snapshotContentEndInclusive: 52960,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/convert-to-html.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/convert-to-html.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 26041,
    snapshotContentEndInclusive: 30204,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/katex-subs.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/katex-subs.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 27453,
    snapshotContentEndInclusive: 30434,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/to-hast-direct.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/to-hast-direct.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s014_unified-latex-packages",
    snapshotContentStart: 23780,
    snapshotContentEndInclusive: 24715,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/unified-latex-to-hast.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/unified-latex-to-hast.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s006_unified-latex-packages",
    snapshotContentStart: 16037,
    snapshotContentEndInclusive: 30168,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/unified-latex-to-html-like.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/unified-latex-to-html-like.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 30537,
    snapshotContentEndInclusive: 33027,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-hast/tests/unified-latex-wrap-pars.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-hast/tests/unified-latex-wrap-pars.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 35641,
    snapshotContentEndInclusive: 37239,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-mdast/tests/convert-to-markdown.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-mdast/tests/convert-to-markdown.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 37336,
    snapshotContentEndInclusive: 39236,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/author-info.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/author-info.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 27785,
    snapshotContentEndInclusive: 31671,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/break-on-boundaries.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/break-on-boundaries.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s013_unified-latex-packages",
    snapshotContentStart: 28832,
    snapshotContentEndInclusive: 37107,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/convert-to-pretext.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/convert-to-pretext.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 36161,
    snapshotContentEndInclusive: 39192,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/exam-to-pretext.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/exam-to-pretext.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s010_unified-latex-packages",
    snapshotContentStart: 31720,
    snapshotContentEndInclusive: 42927,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/expand-user-defined-macros.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/expand-user-defined-macros.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 22733,
    snapshotContentEndInclusive: 24858,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/plus-includes.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/plus-includes.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s012_unified-latex-packages",
    snapshotContentStart: 34149,
    snapshotContentEndInclusive: 40576,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/report-unsupported-macro-katex.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/report-unsupported-macro-katex.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 24968,
    snapshotContentEndInclusive: 27233,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/to-pretext-direct.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/to-pretext-direct.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 27329,
    snapshotContentEndInclusive: 28140,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/unified-latex-to-pretext.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/unified-latex-to-pretext.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s015_unified-latex-packages",
    snapshotContentStart: 170,
    snapshotContentEndInclusive: 78008,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/unified-latex-to-xml-like.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/unified-latex-to-xml-like.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 28245,
    snapshotContentEndInclusive: 30678,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-to-pretext/tests/unified-latex-wrap-pars.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-to-pretext/tests/unified-latex-wrap-pars.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 44832,
    snapshotContentEndInclusive: 46433,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-align/tests/parse-align-environment.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-align/tests/parse-align-environment.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 46536,
    snapshotContentEndInclusive: 48470,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-argspec/tests/argspec-parser.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-argspec/tests/argspec-parser.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 31960,
    snapshotContentEndInclusive: 35292,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/attach-arguments-defaults.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/attach-arguments-defaults.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 45018,
    snapshotContentEndInclusive: 47483,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/attach-arguments-in-array.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/attach-arguments-in-array.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s013_unified-latex-packages",
    snapshotContentStart: 45067,
    snapshotContentEndInclusive: 52351,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/attach-arguments.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/attach-arguments.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s010_unified-latex-packages",
    snapshotContentStart: 43027,
    snapshotContentEndInclusive: 52711,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/get-args-content.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/get-args-content.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 48570,
    snapshotContentEndInclusive: 50361,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/gobble-arguments.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/gobble-arguments.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s013_unified-latex-packages",
    snapshotContentStart: 52451,
    snapshotContentEndInclusive: 60366,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/gobble-single-argument.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-arguments/tests/gobble-single-argument.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s014_unified-latex-packages",
    snapshotContentStart: 42636,
    snapshotContentEndInclusive: 66604,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-arguments/tests/unifiex-latex-attach-arguments.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath:
      "packages/unified-latex-util-arguments/tests/unifiex-latex-attach-arguments.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 50475,
    snapshotContentEndInclusive: 52076,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-catcode/tests/find-region.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-catcode/tests/find-region.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 52169,
    snapshotContentEndInclusive: 53908,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-catcode/tests/regions.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-catcode/tests/regions.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 35611,
    snapshotContentEndInclusive: 38028,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-catcode/tests/reparse-macro-name.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-catcode/tests/reparse-macro-name.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 39746,
    snapshotContentEndInclusive: 44212,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-catcode/tests/special-regions.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-catcode/tests/special-regions.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 47779,
    snapshotContentEndInclusive: 50688,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-comments/tests/delete-comments.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-comments/tests/delete-comments.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 42026,
    snapshotContentEndInclusive: 43089,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-environments/tests/process-environment.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-environments/tests/process-environment.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s012_unified-latex-packages",
    snapshotContentStart: 41114,
    snapshotContentEndInclusive: 47358,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-environments/tests/unifiex-latex-attach-arguments.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath:
      "packages/unified-latex-util-environments/tests/unifiex-latex-attach-arguments.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 54025,
    snapshotContentEndInclusive: 55579,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-glue/tests/glue.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-glue/tests/glue.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 51311,
    snapshotContentEndInclusive: 54361,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-html-like/tests/unified-latex-html-like.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-html-like/tests/unified-latex-html-like.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 41148,
    snapshotContentEndInclusive: 43251,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-ligatures/tests/ligatures.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-ligatures/tests/ligatures.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 46831,
    snapshotContentEndInclusive: 50442,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-macros/tests/list-commands.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-macros/tests/list-commands.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s010_unified-latex-packages",
    snapshotContentStart: 65831,
    snapshotContentEndInclusive: 67984,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-macros/tests/macro-expansion.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-macros/tests/macro-expansion.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s012_unified-latex-packages",
    snapshotContentStart: 47821,
    snapshotContentEndInclusive: 54964,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-packages/tests/list-packages.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-packages/tests/list-packages.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 57655,
    snapshotContentEndInclusive: 59171,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-parse/tests/parse-basic.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-parse/tests/parse-basic.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 44303,
    snapshotContentEndInclusive: 48327,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-parse/tests/parse-override-macros.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-parse/tests/parse-override-macros.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 55135,
    snapshotContentEndInclusive: 56431,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-parse/tests/parse-performance.bench.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-parse/tests/parse-performance.bench.ts",
    license: "MIT",
    role: "benchmark",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s014_unified-latex-packages",
    snapshotContentStart: 66701,
    snapshotContentEndInclusive: 67603,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-parse/tests/parse-varbatim.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-parse/tests/parse-varbatim.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 48421,
    snapshotContentEndInclusive: 53299,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-parse/tests/parse.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-parse/tests/parse.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 50964,
    snapshotContentEndInclusive: 53017,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-pgfkeys/tests/pgfkeys-format.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-pgfkeys/tests/pgfkeys-format.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 54354,
    snapshotContentEndInclusive: 58681,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-replace/tests/replace-node.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-replace/tests/replace-node.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s007_unified-latex-packages",
    snapshotContentStart: 64446,
    snapshotContentEndInclusive: 67595,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-replace/tests/replace-streaming-command.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-replace/tests/replace-streaming-command.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s012_unified-latex-packages",
    snapshotContentStart: 55522,
    snapshotContentEndInclusive: 62668,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-replace/tests/significant-node.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-replace/tests/significant-node.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 63836,
    snapshotContentEndInclusive: 65720,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-replace/tests/unified-latex-replace-streaming-command.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath:
      "packages/unified-latex-util-replace/tests/unified-latex-replace-streaming-command.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s008_unified-latex-packages",
    snapshotContentStart: 65353,
    snapshotContentEndInclusive: 66679,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-scan/tests/prefix-search.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-scan/tests/prefix-search.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s009_unified-latex-packages",
    snapshotContentStart: 67680,
    snapshotContentEndInclusive: 69615,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-split/tests/split.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-split/tests/split.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 59091,
    snapshotContentEndInclusive: 63025,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-to-string/tests/parse.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-to-string/tests/parse.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s004_unified-latex-packages",
    snapshotContentStart: 64489,
    snapshotContentEndInclusive: 66486,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-trim/tests/trim.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-trim/tests/trim.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s011_unified-latex-packages",
    snapshotContentStart: 64060,
    snapshotContentEndInclusive: 68697,
  }),
  Object.freeze({
    id: "unified-latex:packages/unified-latex-util-visit/tests/visit.test.ts",
    producer: "unified-latex",
    producerLineage: "unified-latex",
    upstreamRevision: "3c1350edbc8f13ccfbbd5d96919391fefa4d268d",
    sourcePath: "packages/unified-latex-util-visit/tests/visit.test.ts",
    license: "MIT",
    role: "test",
    correlationLabel: "parent-regression-correlated",
    snapshotRevision: "20260831_115026",
    snapshotShard: "s016_unified-latex-packages",
    snapshotContentStart: 65549,
    snapshotContentEndInclusive: 69339,
  }),
]);
